### ISSUE TITLE
Nuevos atributos y nuevo tipo de Equipamiento 

### ISSUE THREAD

**Issue by paoespinozarias** [opencitydata/sociedad-bienestar-equipamientos-municipales#10]
¿Tiene sentido que un _equipamiento_  tenga como atributos una _fecha de alta_ y una _fecha de baja_? Sería de mucha utilidad si los tuviera para saber, por ejemplo, cuando una estación de bicicleta se dio de alta o baja.  

Adicionalmente, el SKOS de _tipo-equipamiento_ debería incluir también una _Estación de Bicicleta_ en la clasificación de _Circulación y Transporte_, así como tiene una Estación de Metro, Parada de Bus, etc.

**Comment by ocorcho** [comment]
SKOS actualizado en commit 2b5821d82b4d483437ee9040f4cf3f6f43cec642 en el repositorio https://github.com/opencitydata/listas-codigos-skos
